### ISSUE TITLE
Monogame WindowsGL ignores keyboard layout.

### ISSUE THREAD

**Issue by BaseCrosser** [MonoGame/MonoGame#3836]
Greetings,

A few points:
- I'm using MonoGame 3.4
- My keyboard layout is AZERTY
- I have checked my language and keyboard settings on my computer and everything is correct

The problem I'm having is that the OpenGL versions of MonoGame seems to ignore the keyboard layout.

I created a little piece of testing code which is:

``` C#
/// <summary>
/// This is called when the game should draw itself.
/// </summary>
/// <param name="gameTime">Provides a snapshot of timing values.</param>
protected override void Draw(GameTime gameTime)
{
    // Testing fields
    Color clearColor = Color.MonoGameOrange;
    KeyboardState keyboardState = Keyboard.GetState();

    if (keyboardState.IsKeyDown(Keys.Escape))
        Exit();

    // Testing code
    if (keyboardState.IsKeyDown(Keys.A))
        clearColor = Color.Black;
    else if (keyboardState.IsKeyDown(Keys.Q))
        clearColor = Color.White;

    // Show the clearColor
    GraphicsDevice.Clear(clearColor);

    base.Draw(gameTime);
}
```

When I'm pressing the A key the screen turns white and when I'm pressing the Q key the screen turns black. It should be inversed. 
When debugging I saw that MonoGame thinks I have a QWERTY keyboard when in fact I have an AZERTY keyboard. But the GameWindow.TextInput event does not suffer from this error. It gives the correct characters.
When testing this piece of code on the WindowsDX version everything worked just as it should, no problems.

Thankyou for the work you guys are doing.

**Comment by tomspilman** [comment]
> When testing this piece of code on the WindowsDX version everything worked just as it should, no problems.

The WindowsDX path uses XInput2 to get keyboard state which correctly translates between keyboard layouts.

The WindowsGL platform uses OpenTK which I guess isn't doing that translation.

@cra0zy @dellis1972 - Seems like this should be a bug we chase down with the OpenTK team?

**Comment by cra0zy** [comment]
I don't know whether to count this as OpenTK bug or not. Unlike DirectX which has the integration with Windows, OpenTK manually reads from the driver using a pre setup table of indexes so it's understandable that this happens. 

@Frassle @thefiddler What do you think on this?

**Comment by tomspilman** [comment]
> OpenTK manually reads from the driver using a pre setup table of indexes so it's understandable that this happens. 

Ah... we at least I understand where it is coming from then.

Still this seems like something OpenTK should be handling... it can't be returning `Key.A` when it is really `Key.Q`.

**Comment by Frassle** [comment]
Sounds reasonable for OpenTK to do this correctly, bug opened.

**Comment by BaseCrosser** [comment]
Thankyou guys. I will keep an eye on this.

**Comment by Frassle** [comment]
Spent a while on and off looking into this. Rewrote the system to mostly use virtual keys reported by Windows, with some special case handling so we get a better mapping to physical keys (numpad keys change their vkey based on numlock, we don't want that). If you could try it out on your keyboard layout and let me know if there's any keys that are translating incorrectly (or not at all!) that would be a great help! https://github.com/Frassle/opentk/tree/keyboard

I'm aware of at least two issues that AltGr comes through as a LCtrl+RAlt that requires quite a bit to fix as Windows actually sends us to key press messages. Secondly the key next to 1 on the UK keyboard (The one with ¬ ` and ¦ on it) isn't being recognized, that's probably just a case statement I've missed in translating vkeys to OpenTK keys.

**Comment by BaseCrosser** [comment]
@Frassle I tried to build opentk from source from the link i your post but when I added the resulting binary to my application where I encountered the problem with the keyboard my application wouldn't even start. Something with Wgl.cs. Sorry that I can not help you. If you know what I've done wrong please tell me :smile:

**Comment by Frassle** [comment]
Can you build and run the examples? One of the examples is GameWindowStates and it prints a load of debug info to the screen including key presses, if you can run that it's probably good enough to test the keyboard layout for now and then I'll worry about wgl.cs issues.

**Comment by BaseCrosser** [comment]
@Frassle The GameWindowStates example does not exist on your tree. The files opentk-develop\Source\Examples\OpenTK\GameWindow\GameWindowStates.rtf  And  opentk-develop\Source\Examples\OpenTK\GameWindow\GameWindowStates.cs are missing.

**Comment by Frassle** [comment]
Did you checkout the keyboard branch? Also your not building OpenTK correctly, the rewrite code hasn't run to inject the natives calls we need. How are you building? With Visual Studio?

**Comment by BaseCrosser** [comment]
I did accidentally checkout the develop branch. I am building with Visual Studio. Can you give me some instructions on how to build then?

**Comment by Frassle** [comment]
That's odd Visual Studio should be doing the build correctly. At least for me on VS2012 the rewrite is called automatically. If it isn't you can call it manually:
Binaries\Tools\Release\Rewrite.exe Binaries\OpenTK\Release\OpenTK.dll OpenTK.snk

**Comment by BaseCrosser** [comment]
Okay, I got it to work. I was using VS2015 Release Candidate for building but I changed to VS2013 Community now. I got it working but did not test my keyboard layout yet. I've got no time left today so I will test it tommorrow.

**Comment by BaseCrosser** [comment]
@Frassle I tested and a few keys were not correct.
Here is a drawing of what it should be: http://imgur.com/a/jSLKv
Here is my results (Note: the correct keys are removed): http://imgur.com/a/jSLKv

On the keypad there were two keys wrong but I don't have a drawing of them.
The wrong keys are numlock and keypad enter.
Numlock gets registered as pause.
Keypad enter as numlock.

I hope this helps!

**Comment by Frassle** [comment]
Cool thanks that does help, I'll keep looking into it.

**Comment by Frassle** [comment]
Ok, I think I fixed the numlock and keypad issues. AltGr is still problematic (but it's always been problematic). 

Sadly there doesn't seem to be any good way of mapping some of the punctuation keys (e.g. ;'#/\`[]) as windows just returns an OEM virtual key code that doesn't always correspond the same character. I've slightly changed the OpenTK keycodes exposed to mark the current codes for those characters as deprecated and to use Oem codes instead. If we can't do this "right" we'll at least try to be clear about that.

For the most part the new code should map keys to the keyboard layout MUCH better.
https://github.com/Frassle/opentk/tree/keyboard

I'm going to spend a little more time seeing if I can map AltGr to RightAlt as that seems sensible and then I'll see about pushing this to OpenTK master.

P.S @MonoGame team any chance of an OpenTK label or something so we can scan for issues like this easier?

**Comment by tomspilman** [comment]
> I'll see about pushing this to OpenTK master.

Fantastic to hear!  Thanks for you help on this @Frassle !

> P.S @MonoGame team any chance of an OpenTK label or something so we can scan for issues like this easier?

Done!

**Comment by BaseCrosser** [comment]
@tomspilman This problem still exists in the current version of MonoGame. I think it is because of the fork that you are using now doesn't have the changes that @Frassle made merged into it.

**Comment by dellis1972** [comment]
Have you tried the latest development release?

**Comment by mrhelmut** [comment]
The problem still exists, and yes, there's a PR pending here: opentk/opentk#269
I haven't tested it, and it seems to be subject to debate.

GL inputs are currently being reworked on the MonoGame side, though.

**Comment by BaseCrosser** [comment]
Yes, i use Nuget and the current version is 3.5.0.1502.

**Comment by cra0zy** [comment]
This should be fixed with #4755

**Comment by mrhelmut** [comment]
Confirmed.

**Comment by cra0zy** [comment]
@tomspilman This can be closed.
