### ISSUE TITLE
[WinDX] SharpDX "Unsupported" exception when creating graphics device

### ISSUE THREAD

**Issue by MichaelDePiazzi** [MonoGame/MonoGame#5123]
I got the below crash report a little while ago (from a Windows 7 SP1 machine):
```
SharpDX.SharpDXException: HRESULT: [0x887A0004], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_UNSUPPORTED/Unsupported], Message: Unknown
 at SharpDX.Result.CheckError()
 at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
 at Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateDeviceResources()
 at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformInitialize()
 at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Initialize()
 at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
 at Microsoft.Xna.Framework.GraphicsDeviceManager.Initialize()
 at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
 at Microsoft.Xna.Framework.GamePlatform.BeforeInitialize()
 at MonoGame.Framework.WinFormsGamePlatform.BeforeInitialize()
 at Microsoft.Xna.Framework.Game.DoInitialize()
 at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
...
```
The crash occurred while trying to create the graphics device. From what I can tell, it seems like a driver issue (probably a fresh install of Windows without video drivers being installed). Unfortunately I wasn't able to contact the user who reported it (they submitted an invalid e-mail), so I couldn't investigate the cause.

But I guess the main issue here is not that an exception occurred, but that MonoGame threw a SharpDX exception when trying to create the graphics device. I'm not sure, but I think in this case XNA would likely throw a `NoSuitableGraphicsDeviceException` (https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.nosuitablegraphicsdeviceexception.aspx). Does anyone know more about how XNA would handle this?

Thoughts?

**Comment by MichaelDePiazzi** [comment]
FYI - So that I can gracefully handle this situation, what I've done for the time being is added an exception handler to `GraphicsDeviceManager.CreateDevice()` around the `Initialize()` method like so:
```c#
try
{
    Initialize();
}
catch (Exception ex)
{
    throw new NoSuitableGraphicsDeviceException("Failed to create graphics device!", ex);
}
```
This may not be ideal, but it at least tells me specifically if the graphics device failed to be created. I can then show a message to the user asking them to check that their graphics device is compatible and that their drivers are up to date.

I had a look at what FNA is doing in this case, and it is also using this `NoSuitableGraphicsDeviceException` to notify when the graphics device failed to be created (although it's doing more specific checks, rather than a catch-all exception handler like I've done).

Doing a quick file search in MonoGame shows that only the Android build seems to be currently using `NoSuitableGraphicsDeviceException` for this purpose.

So I'm guessing this is the right way forward...

Thoughts? @tomspilman @KonajuGames @dellis1972

**Comment by KonajuGames** [comment]
It's better than the hard crash we get now. More specifics could get added
later.

**Comment by MichaelDePiazzi** [comment]
Cool. Well I've added PR #5130 for now which does this. It also checks for and rethrows any specific `NoSuitableGraphicsDeviceException` which are already thrown. If this isn't sufficient, I'm happy to add any more specifics which might be required.

**Comment by LanceJZ** [comment]
I'm getting this error when trying to use DirectX, it is not a driver issue on my side. They are new and up to date. I have an nVidea Strix 970. This is the inner error.
Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException occurred
  HResult=0x80131500
  Message=Failed to create graphics device!
  Source=MonoGame.Framework
  StackTrace:
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Asteroids.Program.Main() in F:\Documents\Visual Studio 2017\Projects\VS2017C#\MonoGame\AsteroidsMonoGameDX\Asteroids\Program.cs:line 18

Inner Exception 1:
SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

It happens on this line:
using (var game = new Game())
                game.Run();

In Program.CS unchanged from the template except Game1 is now Game, but that makes no difference.

**Comment by Jjagg** [comment]
@LanceJZ That issue is fixed in #5477

**Comment by Hamzart** [comment]
that  issue  is not fixed yet , stop working on desktop only and take a look on Dual GPU Laptops , neither Opengl neither Direct3d projects template worked for me ,  just an empty project  i did nothing else . on Dx 
it throw me an exception Saying that my NVIDIA GTX 1050  doesnt support Reach, profile , i changed to Hdif , it says the same. then what i'm supposed to do with this ? i'm up to date with Nvidea Geforce experience . 


Ok now Go to Desktop  Cross Platforms Opengl template : it throws me another  different exception.
is my GTX 1050 considered as old ? or something ?  



Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException
  HResult=0x80131500
  Message=Failed to create graphics device!
  Source=MonoGame.Framework
  StackTrace:
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Game2.Program.Main() in C:\Users\Hamza\source\repos\Game2\Game2\Program.cs:line 17

Inner Exception 1:
PlatformNotSupportedException: MonoGame requires either ARB_framebuffer_object or EXT_framebuffer_object.Try updating your graphics drivers.

**Comment by MichaelDePiazzi** [comment]
@Hamzart Your GPU should definitely work with MonoGame. I suggest that you create a new issue for this problem you're having. It should get some attention then and hopefully someone can help with fixing it.
