### ISSUE TITLE
Cannot install templated for VS2015/2017 on Windows 10

### ISSUE THREAD

**Issue by Jixxis** [MonoGame/MonoGame#6196]
Since having to wipe my hard drive, I've been trying to open my MonoGame solutions on my fresh Windows 10 install. I've installed VS 2013, 2015, and 2017 but when I run the MonoGame 3.6 installer the only components I can install are the MonoGame Core Components and the Star Menu Shortcuts. All of the boxes ranging from the VS2010 to VS2017 templates are both unchecked and greyed out so I cannot check them.

I've been scouring Google for the past 3 hours and can't for the life of me figure out why these templates cannot be installed on my machine. Can anyone help?

![image](https://user-images.githubusercontent.com/36606285/36355636-54a3927c-14b4-11e8-9e6c-31fa138198e7.png)

**Comment by Jixxis** [comment]
Finally figured it out. For anyone else having this issue, there needs to be a C# folder in your templates. BUT your system might have configured itself to use your OneDrive. 

To check where your system points to, you'll need to open regedit and navigate to Computer\HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0 if you have VS2015 installed (Why it's under 14.0 and not 15.0 I have no idea), then check UserProjectTemplatesLocation to find which location it's pointing to. After that, just make sure that your Documents\Visual Studio 2015\Templates\ProjectTemplates\ folder has a "Visual C#" folder within it, and add it if it doesn't. Same deal with VS2017

Now if only I could figure out why I can't make a new MonoGame Windows 10 Universal Project and why this error keeps popping up in my existing ones: 
"The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

**Comment by KakCAT** [comment]
I'm not sure if this will also apply in your case, but I've had the 'not referenced' error sometimes and I've fixed it by updating the Microsoft.NETCore.UniversalWindowsPlatform nuget package.

If you're updating it with VS2015 be alert because for some reason not all versions work (I think 5.2.3 is the last one that worked). No problem with VS2017 yet.

**Comment by Halofreak1990** [comment]
> I'm not sure if this will also apply in your case, but I've had the 'not referenced' error sometimes and I've fixed it by updating the Microsoft.NETCore.UniversalWindowsPlatform nuget package.

Yeah, the Microsoft.NETCore.UniversalWindowsPlatform package that the MonoGame UWP template references doesn't work. One of the sub-packages (something along the lines of "Microsoft.NetCore.Jit" version 1.0.3) apparently doesn't support _any_ of the UWP versions. But any later version is fine.

**Comment by bsp-github** [comment]
The problem still seems to exist.   Tried to install MonoGame on Windoes 10 / VS 2017 Community as an administrator - it fails to install the templates.   

![monogamesetup](https://user-images.githubusercontent.com/34964974/47057087-198eca80-d174-11e8-8d04-e34ee90d5b5f.png)

**Comment by bytemarq** [comment]
I had the same problem with Monogame 3.7.1.  Here is how I got it to work, no sure if this was specific for me or not.  My setup is Windows 10 Home (1903) Visual Studio 2017 Community Edition.

I checked my Virus Software and found that it had blocked a call by the installer on the Firewall, so I unblocked the installer.  Then I ran the installer with the templates for 2015/2017 unchecked.  That installed without error.  I then ran the installer again and left VS2017 Templates selected (but I still unchecked VS2015 templates) and this time it installed without any errors.
:) Hope this helps someone.

**Comment by bytemarq** [comment]
One problem that remains though is that the Content Pipeline tool does not automatically open when I double click on the Content.mgcb
Where is the Content tool installed on Windows 10, anyone?
