### ISSUE TITLE
XNB content files are not copied when publishing project

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#7912]
I have a monogame project that depends on a class library project that also contains content files compiled by MGCB.

- When compiling in Debug/Release, all the files are copied correctly.
- When publishing to a folder, only the XNBs of the main project are copied, the XNBs of the dependencies are missing.

I also included a regular content file to the class library, and it's correctly copied when publishing.

I've included a repro: [MonoGamePublishExample.zip](https://github.com/MonoGame/MonoGame/files/9373912/MonoGamePublishExample.zip)

The solution has a main project and a class library project.
- The Main project has Content A, which is always compiled and copied.
- The Class Library project has two contents:
  - Content B, which is a regular content file that is copied when building and publishing.
  - Content C which is a monogame content file that is converted to XNB and copied when building, _but is missing on publish_.

So maybe, Monogame.Content.Builder.Task target needs additional steps to handle publishing content?

Additional Context: With Net6.0, this is relevant because we want to compile to _single file executables_, which seem to be available only during publish.

Related to: [publish-doesnt-copy-content/11671](https://community.monogame.net/t/publish-doesnt-copy-content/11671)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by vpenades** [comment]
Well... apparently the issue was caused by a specific version of VisualStudio that was messing with the cached results of some csprojs.. it's been resolved in a recent VS update.

Closing.

**Comment by damian-666** [comment]
i spend hours on this using the latest VS studio preview vw 2022  .. in your user folder and temp folder there are tons of recent Cache files. used to speed up compilaton.. i also still get warning that it cannont detect if a dependency is updated,  bnut and if i touch a resource in a core dll it does only get rebuilt and copy to the exe.  so subsequnt builds are faster, thatn rebuild all,  adn the issues is gone, i ignore this warning.   i deleted all those cache files as they are obvously teh date teh trouble started.. and it went away..  I don't remember the specifics but it cost me alot of time.  I suggest searchng the disk and sort by most recent...

**Comment by vpenades** [comment]
Yes, I sorted it out as a combination of updating VS, clearing caches, and even deleting the whole project and checking it out back to a clean setup.

Apparently, something has changed recently in VS that doesn't handle well cache files created by previous VS versions. so if you try to run with a newer VS with older cache files, everything's messed up.

My feeling is that Microsoft is trying to improve performance of VS at all costs, and they're relying too much on those cache files.

**Comment by damian-666** [comment]
welll its working...   i used to spend 5 min waiting for a debug session on android/ xamarin to start.. now on the 2d launch its coming up in seconds.. usable.  a clean git clone and  setup didn t help me and the  caches were everywhere in my user folders, and even in temp... with weird extensions.. can tell by the date , and the user location , its safe to just delete them.   anything with a date when things went wrong.   Because   i revert my code, or so back to last working build,and its still broken..     i also cleared all nuget packages.

#offtopic: .  so im being reckless and taking each update as it comes i think they have a fairly solid leadership now.. a are going in the right direction (cloud service) both for investors as us,  as a sife effect..at least with core tech if not UI.. . id love if to develop on ARM surface thats not blowing 400 watts in my hotel in Nicaragua , for ARM Android running natively in ARM windows and when i talk to the dev team for a coffee chat they said its can be done... i paid 2500 for this surface , pen still useless to edit or debug ( i told them , they dind tcare)  and its hot and slow and the ARM one is like 800 bucks...i guess its the cloud business driving this effort, all of us benefit from the performance i get with each Net core update wo breaking much code. 
 fine w me.  more efficent = less power , more profit. 
 
  Also from the "coffee chatr" was clear from their questions ( ask me if im using Tortoiise i said yea, but if u add on file stageing to right click id use git in vs studio..)   their agenda is also Git on explorer, visual git.  more data minig ,  for them, fine.   i told them why git rebase/ merge / branch is crazy difficult even on two machines...  and to add easy staging and mmake pen work as least as well as trackpad in tablet mode to debug stuff..  vs 2022 preview has a code /feature search so you can type exceptions and find deeply nest dialogs settings... i told them add that to windows Start , dont lauch Bing tell me how to find the UI.. ..  they are doing better ..with a maybe tiny bit regression each update..
