### ISSUE TITLE
macOS and Linux setup experience

### ISSUE THREAD

**Issue by ThomasFOG** [MonoGame/MonoGame#8124]
I'm creating this issue to centralize all of the other issues to setup a MonoGame project on macOS or Linux.

It is a set of different issues degrading the setup experience on those systems. They are aggregated with the [setup label](https://github.com/MonoGame/MonoGame/labels/Setup), most of them being duplicates.

How to fix those:
- [ ] Build all native dependencies with ```osx-arm64``` support (this is currently being done by refactoring the dependencies into separate projects so that MonoGame can built it own native dependencies without relying on third-parties)
  - [x] SDL
  - [x] FreeType (needs to be wired and tested with SharpFont)
  - [x] FreeImage
  - [x] ffmpeg/ffprobe
  - [x] assimp
  - [x] Replace ATI.TextureCompression, PVRTexLib and NVTT with "basis universal"
  - [x] Hook all packages with the pipeline
- [ ] Fix ```mgfxc_wine_setup.sh```
   - [x] Change the .NET SDK link to .NET 8.0
   - [x] Update WineHelper.cs comments to .NET 8
   - [x] Check for Wine version requirement (there is a minimum version required)
   - [x] Enhance the script to support both 32 and 64 bit versions of Wine (some users have both installed and stuff got installed on the 32 bit version instead)

**Comment by AristurtleDev** [comment]
@mrhelmut 
- Change the .NET SDK link to .NET 8.0: Completed in #8218 
- Update WineHelper.cs comments to .NET 8: Completed in #8219 
- Check for Wine version requirement (there is a minimum version required): Completed in #8220

**Comment by AristurtleDev** [comment]
>  Enhance the script to support both 32 and 64 bit versions of Wine (some users have both installed and stuff got installed on the 32 bit version instead)

Ok so the problem seems to be that monogame assumes that the Linux user is using apt and installed wine64.

But if you install wine like normal using like winehq-staging, then you get both 32-bit and 64-bit support.

Setting the 64-bit support is just the WINE_ARCH flag.

The script would need to be changed to **not** check for the assumption of wine64 and instead just check for just plain wine, then carry on from there. But there needs to be a way to ensure that 64-bit support was also installed

Thoughts @mrhelmut @harry-cpp

**Comment by AristurtleDev** [comment]
`dpkg -l | grep wine` will output

```
aristurtle@ubuntu-personal:~/ftp$ dpkg -l | grep wine
ii  fonts-wine                           5.0-3ubuntu1                          all          Windows API implementation - fonts
ii  libwine:amd64                        5.0-3ubuntu1                          amd64        Windows API implementation - library
iU  wine-staging                         9.3~focal-1                           amd64        WINE Is Not An Emulator - runs MS Windows programs
iU  wine-staging-i386:i386               9.3~focal-1                           i386         WINE Is Not An Emulator - runs MS Windows programs
ii  wine64                               5.0-3ubuntu1                          amd64        Windows API implementation - 64-bit binary loader
iU  winehq-staging                       9.3~focal-1                           amd64        WINE Is Not An Emulator - runs MS Windows programs

```

so the check for wine64 can be made there

**Comment by tomspilman** [comment]
So on this one:

> Replace ATI.TextureCompression, PVRTexLib and NVTT by more suitable texture compressors (candidates are compressanator on Windows/Linux, and TextureConverter on macOS)

The decision the board made is  finding one library we can add just for Mac and Linux.  We will not currently be replacing the existing libs.

What are good candidates?

@mrhelmut @AristurtleDev @harry-cpp  ?

**Comment by dogruis** [comment]
> So on this one:
> 
> > Replace ATI.TextureCompression, PVRTexLib and NVTT by more suitable texture compressors (candidates are compressanator on Windows/Linux, and TextureConverter on macOS)
> 
> The decision the board made is finding one library we can add just for Mac and Linux. We will not currently be replacing the existing libs.
> 
> What are good candidates?
> 
> @mrhelmut @AristurtleDev @harry-cpp ?
Have a look at 
https://github.com/KhronosGroup/KTX-Software

**Comment by mrhelmut** [comment]
The current route that we're looking into is to use "basis universal". It has been prepared for MonoGame, but still need to be hooked into MGCB: https://github.com/MonoGame/MonoGame.Tool.BasisUniversal

KTX-tool uses basis universal under the hood, and we don't need the KTX format.

**Comment by mrhelmut** [comment]
@harry-cpp should we also have mojoshader in its own package? It is only for Windows and less likely to have to be updated, but once we will have everything else moved and linked, mojoshader is basically the only thing left being used in the dependencies repo (which is tempting to just delete and stop having submodules). What do you think?

Ah we would also need to package up OpenAL if we want to blast the dependencies repo.

**Comment by harry-cpp** [comment]
Thats the idea, tho the above was the minimum needed stuff 😄

**Comment by mrhelmut** [comment]
Gotcha! I'm going to check what I can do.

**Comment by SamFold** [comment]
Hi there! Am I correct in assuming there is an ongoing issue using mgcb on an M-series Mac on Sonoma? 

I'm developing on a Macbook Air M3 with Sonoma 14.5, and I've been trying unsuccessfully to get the mgcb editor to run for some time now. Are there any fixes (even hacky ones) yet?

**Comment by dogruis** [comment]
https://community.monogame.net/t/monogame-content-builder-on-mac-m1/20411
https://community.monogame.net/t/tutorial-for-setting-up-monogame-on-m1-m2-apple-silicon/19669

This got me started but it's a workaround for the moment. You have to install two versions of .NET6 because the mgcb uses old dlls

**Comment by ThomasFOG** [comment]
Are there still any outstanding issues that make Linux or macOS not trivial to develop on?

**Comment by jessatech** [comment]
> Are there still any outstanding issues that make Linux or macOS not trivial to develop on?

The primary reason I don't use Monogame right now for some of my game projects is the requirement of this workaround for ARM users on M series silicon.

> You have to install two versions of .NET6 because the mgcb uses old dlls. Note when you want to run the mgcb you have to set the PATH and restart vscode. Then once you are done with mgcb you have to change your path again to not include old .NET6 path. It's wonky but it does the job

This is non-trivial, prone to breaking, and very disruptive once configured which just made Monogame a non-starter vs RayLib, which has since resolved issues with quickly getting started on M series due to a requirement to build from source for ARM by evolving their quickstart project to support ARM platforms out of the box. I know both C++ and C#, so buy-in isn't language based for me.

Beyond getting it setup, needing to run SDKs through Rosetta/Wine and switch between the two introduced a ton of uncertainty around the development and build process and presents some support issues with dev tooling, I think even VS Code warns this isn't supported.

My main issue with switching to MonoGame was that ARM on Mac hadn't been properly supported and was slated for the next release that required the massive rebuild or navigation away from BRUTE to NativeAOT, which I think was the key piece holding back unified/native ARM support on Mac.

If that's all been fixed, then I'll check out Monogame this weekend. If the above is not resolved and I can't avoid Rosetta or Wine and just work with .NET 8 ARM on Mac M-series, it's a non-starter. I can't trust developing multi-year projects, with potential cross-platform targets, through a workaround emulation layer on Apple silicon Macs. 

Saying Mac (OpenGL) is supported, while true, it is a bit misleading when considering the above and given the workarounds required. On Mac, x86 was dropped almost 5 years ago for ARM and OpenGL support has been essentially placed into maintenance mode with Mojave 10.14 in 2022 and is no longer "supported" by Apple.

So proper ARM and Metal support, or at least MoltenVK, are top of my mind. 

I think the NativeAOT work in #8194 is relevant for Apple Silicon Macs as well. It was mentioned to be for consoles but I think it is also used for native compilation on Mac for Universal binaries and would likely be a nice win towards support for Apple silicon.

**Comment by dogruis** [comment]
I still have issues running mgcb on mac I used the tutorial [here](https://docs.monogame.net/articles/tutorials/building_2d_games/)

But when running from the command line I get errors without log or output:
`dotnet mgcb-editor ./Content/Content.mgcb`

<img width="899" height="548" alt="Image" src="https://github.com/user-attachments/assets/ba8eea2d-7bd3-452a-87aa-b491646bc3da" />

I can only run the MGCB by opening vscode and run a vs code command:

<img width="707" height="92" alt="Image" src="https://github.com/user-attachments/assets/b7688dd2-98dc-4e2f-aed6-a77fb2d576b6" />

I find this very odd to have all these workaround.

**Comment by dogruis** [comment]
Also it is worth nothin when using the MGCB from the vs code command I cannot add a new item and change its file extension. Only the filename.

<img width="903" height="552" alt="Image" src="https://github.com/user-attachments/assets/e9f08ab6-89f5-4459-8898-40ad186766ab" />

I have a mac M1

<img width="222" height="115" alt="Image" src="https://github.com/user-attachments/assets/eb0852b6-7d16-4b53-a4bc-0f3a41761cdb" />

**Comment by ThomasFOG** [comment]
@jalder89 I'm sorry but your comment is bit complicated to read and to assimilate because it mixes concerns and present/past experiences (although I understand the negative sentiment and am here to read it). I'd like to focus on the present. If you have the time and will to give it another go, your feedback would be appreciated. Work has been done to not require .NET6 anymore and every bits of monogame should be built for arm by now, therefore not requiring rosetta. Wine is still a thing (but we're soon shipping vulkan/moltenVK which won't require it), but beside this I'm here to check that the other topics are cleared.

The goal of this open discussion is to make sure that the experience throughout all systems is the same.

---

I'm not sure to understand your concern on BRUTE or NativeAOT. Making universal mac builds with (or without) NativeAOT has been a thing for some time now. I've been shipping builds for many games that way since .NET 5. The maybe confusing part that used to exist, was that builds made with monogame were ```osx-arm64``` compliant, but developing needed rosetta.

Anyway, you can just ```dotnet publish -r osx-arm64``` with or without ```PublishAot```, that will work. No rosetta.

BRUTE on the other hand was not meant for desktop.

---

@dogruis that looks like issues we're aware of and trying to fix.

**Comment by jessatech** [comment]
@ThomasFOG actually, no real negative sentiment toward MonoGame, more just that I couldn't justify building on my Mac due to the headaches around x86 on ARM for .NET. MonoGame itself looks great for the projects I wanted to work on but I just can't make myself dev on a Windows machine for the life of me and the friction pushed me to Godot.

> Every bit of monogame should be built for arm by now, therefore not requiring rosetta. Wine is still a thing (but we're soon shipping vulkan/moltenVK which won't require it), but beside this I'm here to check that the other topics are cleared.

This clears most of my concerns, I do not want to have to install x86 .NET SDKs under Rosetta to use MonoGame and need to switch between the two in order to use MGCB or any other aspect of MonoGame. MoltenVK would be great, Metal eventually would be even better. 

Removing emulation from the equation is really the non-trivial blocker for me, using RayLib or any of the big engines just works natively on Mac now. I like C# more than C++ but I don't like Unity and Godot's C# is still a second class language in Godot 4 for now. So MonoGame fit perfectly into the hole I was looking to fill, but not natively enough on my M3 MBP 😂 

I was running into a similar issue as dogruis with MGCB and needed x86 .NET through Rosetta to even get it to open before, but it has been 6 months to a year since I tried and I had basically just decided to use Godot until 3.9

I'll give it a go this weekend, tomorrow is my Friday this week. I'll report back with my thoughts or roadblocks.

**Comment by dogruis** [comment]
@ThomasFOG I installed the latest stable tag v3.8.4. And I am happy to help with this if there is a new version that should be tested.

**Comment by ThomasFOG** [comment]
> [@ThomasFOG](https://github.com/ThomasFOG) I installed the latest stable tag v3.8.4. And I am happy to help with this if there is a new version that should be tested.

If you wish to try the in-progress release, the current bleeding edge packages are ```3.8.5-develop.11```. Make sure to update that in your ```.config/dotnet-tools.json``` for the MGCB editor to pick it up.

**Comment by jessatech** [comment]
@ThomasFOG so far no issues with working and building on ARM as of 3.8.4
> M3 Max
MacOS Sequoia 15.5

MGCB is also working via the VS Code extension button and the command palette but I do get the same error as dogruis when running via the CLI. I don't think I would ever use the CLI over the extension or command palette, but perhaps it is useful for certain situations I'm just not aware right now.

So looks like needing x86 version of .NET via Rosetta to use MGCB is fixed and I was able to add content and build the project, that was my biggest complaint. Thanks for the notification on this, I probably wouldn't have come back for awhile otherwise.

Will work on completing the full tutorial next weekend, but for now, all seems to be good. Looking forward to MoltenVK in the future. 😄

**Comment by ThomasFOG** [comment]
Thank you for your time and your feedback.

I'm leaving this opened until we figure out the editor being empty (which I think is related to working directory).

**Comment by Bamboy** [comment]
Are there known issues with Fedora Linux systems? Getting the toolkit fully working has been a real big headache for me. (I'm running Nobara 42 specifically)

A few mystery MGCB-Editor problems were resolved when I built from source (develop branch). Most notably, the app not being able to find the mgcb. IMO __mgcbSearchPaths_ in _PipelineController.cs_ should contain common nuget directories. Nuget is likely the way most users are going to going to be getting the monogame tools. A fallback "preference" menu to enter your own mgcb path might be nice too, in case all goes wrong.

I haven't **ever** been able to get the effects compiler to work - I actually just spent 5 hours trying to reverse engineer the problem to get something working. Did a bunch of tinkering with Wine, the source code+debugger, environment variables, different versions of the setup shell script, .Net versions, entering terminal commands that the program sends, nothing works. The only thing I can conclude is that Wine is bugged, or the distributed version of fxccs.dll is.

I attached a bunch of my logs and notes about my system and other stuff if anyone wants to take a look.
[monogame_logs.txt](https://github.com/user-attachments/files/22309169/monogame_logs.txt)

**Comment by jessatech** [comment]
> If you wish to try the in-progress release, the current bleeding edge packages are `3.8.5-develop.11`. Make sure to update that in your `.config/dotnet-tools.json` for the MGCB editor to pick it up.

Quick update, I went ahead and tested 3.8.5-develop.11 and MGCB crashes with the same error mentioned by dogruis after updating `dotnet-tools.json` and doing a clean restore.  

So MGCB works for adding existing files and loading textures in 3.8.4, such as logo.png or atlas.png from the 2D tutorial. However, it crashes in `3.8.5-develop.11` and the blank new file selector previously mentioned blocks creating things like XML Content via the add new file flow from [Chapter 7 of the 2D tutorial](https://docs.monogame.net/articles/tutorials/building_2d_games/07_optimizing_texture_rendering/index.html#using-the-textureatlas-class:~:text=Add%20%2D%3E%20New%20Item%20%2D%3E-,XML%20Content,-%22.).

I just thought I would share back here that trying to update to the 3.8.5 develop package results in the MGCB crash and 3.84 opens and works for loading existing files.

**Comment by grillonbleu** [comment]
Is building shaders still broken in mgcb 3.8.4 for Linux? I'm on Mint, I've followed [the tutorial](https://docs.monogame.net/articles/getting_started/1_setting_up_your_os_for_development_ubuntu.html), executed the [bash script](https://monogame.net/downloads/net8_mgfxc_wine_setup.sh) and I've tried all sorts of tricks floating around the web, but I can't get it to work. The `.fx` file fails to build and gives no error message, either through the CLI or the editor.

**Comment by Apostolique** [comment]
I have this project that builds with shaders that build under Linux: [Mitten](https://github.com/Apostolique/Mitten).

You can see the commands that I run: <https://github.com/Apostolique/Mitten/blob/main/.github/workflows/release.yml>.

**Comment by powerbf** [comment]
> Is building shaders still broken in mgcb 3.8.4 for Linux? I'm on Mint, I've followed [the tutorial](https://docs.monogame.net/articles/getting_started/1_setting_up_your_os_for_development_ubuntu.html), executed the [bash script](https://monogame.net/downloads/net8_mgfxc_wine_setup.sh) and I've tried all sorts of tricks floating around the web, but I can't get it to work. The .fx file fails to build and gives no error message, either through the CLI or the editor.

I was getting this problem on Linux Mint 22.1 with Wine 9.0 and Monogame 3.8.4.1. The shader (.fx) compilation was failing without any error message, except to say that the process exited with exit code 1.

After several days of experimentation and banging my head against a wall, I was able to track down the issue. On Linux, the shader compiler (mgfxc) internally runs "wine dotnet mgfxc.dll <args>". This command was failing because it couldn't find dotnet.exe when it was in ~/.winemonogame/drive_c/windows/system32. I think this is because wine is redirecting windows/system32 to windows/syswow64 in the background. I tested this by dropping some random exe in windows/system32. Wine couldn't find it there, but when I dropped it in windows/syswow64, wine was able to find it.

Anyway, I was able to work around this issue by modifying net8_mgfxc_wine_setup.sh so that it extracts dotnet-sdk.zip into $WINEPREFIX/drive_c/windows/ instead of $WINEPREFIX/drive_c/windows/system32/. Then I blew away ~/.winemonogame and ran the script again, and all was well. Hopefully, this information will be helpful to anyone else who encounters this problem.

**Comment by SireBeef** [comment]
> Anyway, I was able to work around this issue by modifying net8_mgfxc_wine_setup.sh so that it extracts dotnet-sdk.zip into $WINEPREFIX/drive_c/windows/ instead of $WINEPREFIX/drive_c/windows/system32/. Then I blew away ~/.winemonogame and ran the script again, and all was well. Hopefully, this information will be helpful to anyone else who encounters this problem.

For arch linux, I had to modify the script this way and also set `export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true` due to missing ICU library functions.

**Comment by dellis1972** [comment]
@SireBeef  would you be able to make a PR on https://github.com/MonoGame/monogame.github.io/blob/main/website/content/public/downloads/winesetup/net9_mgfxc_wine_setup.sh (and the other setup scripts?) or let us know exactly where you added that `export`?

**Comment by SireBeef** [comment]
@dellis1972 I definitely could open a PR for that but I'm not so sure it's the right solution for everyone.  I see two separate issues here.

1.)  I think, based on this discussion fixing the path is definitely something that needs to be done for wine 9.0+. I'm on 10.0 and encountered the same path issue with the script as @powerbf who was on 9.0.  I'm not sure about 8 and it seems like the script accepts any wine version 8 or above.  Maybe the path problem wasn't an issue when the script was originally written with wine 8 in mind, but it is a problem now with 9.0+ -- would need to do some various testing to confirm. 

2.) To answer your question about where I set  `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true`.  I just set it as an environment variable in my ~/.profile.  This means it 1. it disables culture-aware string comparisons, 2. there is edge case potential to cause cross-platform behavioral differences if someone pulled down a project that depended on the ICU libraries. and 3. Setting this env var effects not just monogame, but any and all .NET apps launched in that environment <--- This is a decision I don't think we should make on behalf of all users without their explicit opt-in.  I can think of a couple potential solutions:  The first would be just document the missing ICU libraries error in the troubleshooting steps and let people opt in themselves to that env var.  The second would be to build some sort of wrapper env variable and set that in the install script -- something like: MG_DOTNET_SYSTEM_GLOBALIZATION_INVARIANT and if that's set to true, wire that in to the command when launching wine (I dont know where that code is though).  thoughts?

**Comment by dellis1972** [comment]
@SireBeef  so i think the thing we actually need to do with `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` is to set that as an envvar when we launch the app in wine in here https://github.com/MonoGame/MonoGame/blob/develop/Tools/MonoGame.Effect.Compiler/Effect/WineHelper.cs#L77

**Comment by harry-cpp** [comment]
With the latest development release of MonoGame we are no longer relaunching the entire mgfxc under wine so `InvariantGlobalization` stuff should no longer be an issue.

If it turns out that its still causing issues, feel free to open a PR and ping me in it, I will take a look asap 😄 

Closing this down as the original issues have been resolved.
