### ISSUE TITLE
DesktopVK - Textures not correctly bound

### ISSUE THREAD

**Issue by TheKrumpet** [MonoGame/MonoGame#8833]
### Prerequisites

- [x] I have verified this issue is present in the `develop` branch
- [x] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

MonoGame develop - DesktopVK

### Which MonoGame platform are you using?

N/A

### Operating System

Windows

### Description

There appear to be an issue where sometimes a texture doesn't appear to be bound correctly to a shader, resulting in any attempt to sample that texture returning 0.

I'm not sure what exactly is causing it. but I've got a small sample project with a simple deferred renderer which exhibits the behaviour. It's in the VKRepro.TextureNotBound project.

I can see in RenderDoc, that in the forward pass, the maps are being correctly populated, so there's definitely data in the textures:

![Image](https://github.com/user-attachments/assets/8052cfcf-777b-4afd-a626-580d2a3dbd9a)

But when it comes to drawing the final scene, there's no textures bound at all:

![Image](https://github.com/user-attachments/assets/ea4b0a7b-7275-4e34-8b28-2c1f77e7c5bf)

Additionally, there's the following error in renderdoc:

![Image](https://github.com/user-attachments/assets/a0a15cc7-d532-430f-bc6e-9c515a05bff4)

This error references the `vkCmdDraw` where the final frame should be drawn into the back buffer.

### Steps to Reproduce

Run the VKRepro.TextureNotBound in the attached project.

### Minimal Example Repo

https://github.com/KristianFenn/VKRepro

### Expected Behavior

The texture is bound correctly.

### Resulting Behavior

The texture isn't bound, meaning all samples return 0. (It's surprising to me that it doesn't just crash).

### Files

The renderdoc capture is available at https://github.com/KristianFenn/VKRepro/blob/main/VKRepro.TextureNotBound/VKRepro.rdc

**Comment by ThomasFOG** [comment]
Should be fixed with #8957

**Comment by TheKrumpet** [comment]
@ThomasFOG I've retested this after those fixes were merged, and the issue persists. The textures just aren't getting bound in the deferred pass.

**Comment by tomspilman** [comment]
hey @TheKrumpet .

I wonder if your card happens to be one affected by the swapchain regeneration issue.

If you have the time can you try these fixes:

https://github.com/MonoGame/MonoGame/pull/9044

**Comment by TheKrumpet** [comment]
@tomspilman That branch unfortunately doesn't seem to have made a difference.

To elaborate on what I'm seeing, I just get a completely black output screen. I know that _something_ is drawing because I clear to cornflower blue before the deferred pass, so the buffer is getting overwritten with just 0 samples. I also have a debug technique for the shader which will just draw a texture coordinate gradient which displays fine, so the quad I'm rendering to is in the right place.

In render doc I see the following error:
<img width="893" height="94" alt="Image" src="https://github.com/user-attachments/assets/ce276a50-9645-4565-8e48-39c5eb2db669" />

Which (I think) references this descriptor with id 31:
<img width="1109" height="343" alt="Image" src="https://github.com/user-attachments/assets/1c352db3-ddf3-4730-ae48-ac8d240ae780" />

Which does in fact not have an index 34:
<img width="616" height="217" alt="Image" src="https://github.com/user-attachments/assets/b96bd988-0b07-42b4-9c44-8f16f4a5019b" />

If I look at the bindings that are there, the textures I can see are the normals and albedo for the sphere from the gbuffer pass, which seems like it's not correctly changing the texture bindings when changing the shader mid-pass. My suspicion would be around shader switching at the moment. I did have a quick step through the code with the debugger and I can't see anything _obviously_ wrong, but I'm far from an expert at that low a level so I wouldn't necessarily expect myself to notice.

**Comment by tomspilman** [comment]
I'll find some time to debug your test project with the latest and figure out why.

**Comment by tomspilman** [comment]
This is fixed in #9044.

**Comment by tomspilman** [comment]
@TheKrumpet did this fix you?

**Comment by TheKrumpet** [comment]
Yes, this works as expected now.
