### ISSUE TITLE
MGCB Editor not showing possible file types in the "Add > New item..." dialog

### ISSUE THREAD

**Issue by zignd** [MonoGame/MonoGame#9113]
### Prerequisites

- [x] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

3.8.4.1

### Which MonoGame platform are you using?

MonoGame Cross-Platform Desktop Application (mgdesktopgl)

### Operating System

macOS 26.1

### Description

On macOS, when I open the MGCB Editor and try to add a new item (Add > New item...), the dialog doesn't show the possible types.

<img width="912" height="564" alt="Image" src="https://github.com/user-attachments/assets/db28a1c5-be91-4066-bc24-6b824914ac4b" />

### Steps to Reproduce

I was following the oficial tutorial for 2D Games and when I reached [Building 2D Games > Chapter 05: Content Pipeline > Adding Built-In Asset Types](https://docs.monogame.net/articles/tutorials/building_2d_games/05_content_pipeline/index.html?tabs=vscode#adding-built-in-asset-types), I noticed the difference from the screenshot of MGCB Editor in the page to what actually opened for me on macOS.

### Expected Behavior

I was expecting to see the same types of files listed in the screenshot of the tutorial, like this:

<img width="1332" height="816" alt="Image" src="https://github.com/user-attachments/assets/9a1cdcb0-b9ce-4e5b-83fc-b21e03c859b1" />

But what I saw was the image I attached in the description previously.

### Resulting Behavior

I didn't notice error pop-ups when the application opened.

**Comment by dellis1972** [comment]
This should have been fixed via https://github.com/MonoGame/MonoGame/pull/8841 Looks like it wasn't released in 3.8.4.1. 
Its fixed in the 3.8.5-develop.* releases though.

**Comment by zignd** [comment]
@dellis1972 I just tried to run the MGCB Editor in a new project (created using the "MonoGame Cross-Platform Desktop Application" template in VS Code) where I updated the `.dotnet-tools.json` tools and the project `.csproj` dependencies to point to `3.8.5-develop.13`. Ran `dotnet tool restore` and rebuilt the project to refetch the dependencies, and this happens when I try to open the default Content.mgcb file.

<details><summary>Here's the content of the Content.mgcb file:</summary>
<p>

```
#----------------------------- Global Properties ----------------------------#

/outputDir:bin/$(Platform)
/intermediateDir:obj/$(Platform)
/platform:DesktopGL
/config:
/profile:Reach
/compress:False

#-------------------------------- References --------------------------------#


#---------------------------------- Content ---------------------------------#

```

</p>
</details> 



<img width="898" height="548" alt="Image" src="https://github.com/user-attachments/assets/1f9baf88-fe22-4374-83c4-0a52944ff904" />

**Comment by dellis1972** [comment]
@zignd the last bug is covered by #9119

**Comment by justdanharrison** [comment]
I'm having this issue as well. How do we get this fix deployed as a NuGet package?

**Comment by dellis1972** [comment]
you update your nuget packages  in your csproj and your .config/dotnet-tools.json to use `3.8.5-develop.12`
Its the same as https://docs.monogame.net/articles/getting_to_know/howto/HowTo_Install_Preview_Release.html. But you use the develop releases

**Comment by justdanharrison** [comment]
I don't think 3.8.5-develop.12 or 3.8.5-develop.13 include that fix as #9122 was merged only last week? That, or there's some other reason for it to not work when I try 3.8.5-develop.13 locally on my Mac running 26.1

**Comment by dellis1972** [comment]
Sorry, this is the `Add -> New Item ` bug I assumed you were talking about that. Not the other one mentioned https://github.com/MonoGame/MonoGame/issues/9113#issuecomment-3594187568. 

There is no release for that yet.

**Comment by dellis1972** [comment]
3.8.5-preview.1 is out, that should contain the various merged fixes. The crash was fixed via https://github.com/MonoGame/MonoGame/pull/9122

**Comment by jeffsnff** [comment]
I wanted to add to this because I also just ran into this issue. 

TL:DR
- Rider - Unable to see types
- VS Code - Able to see types

I am still seeing this issue in Rider with the 3.8.4.1 Preview 4 ( I think, I might need someone to jump on a call with me to get the exact specifications )

However, when I tried various solutions provided by the community, and I wasn't seeing the Type in the MGCB Editor in Rider, I decided to open the project in VS Code and I do see the types there. I installed both Monogame extensions that were available.
